### PR TITLE
data-producers variable in update.sh does not support multiple accounts

### PR DESCRIPTION
**Pull request by mservidio**
Fies #438, #425

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [X] Does your submission pass tests?
2. [X] Have you lint your code locally prior to submission?

### CODE REVIEW

**Review by swilliams11 — COMMENTED** [review]
This change is going to break the current Marketplace release.

**Comment by mservidio** [comment]
@swilliams11 I tried a couple of things, and I think it will work ok as is. The issue that we had, was with wildcards from what I recall. I was able to work around that by including the double quotes within the string:

`export DATA_PRODUCERS='"*@google.com"';`

**Review by mservidio — COMMENTED** [review]
LGTM

**Review by swilliams11 — APPROVED** [review]
LGTM

**Pull request merged**
